openapi: 3.0.3
info:
  version: 1.1.0
  title: LitVar API
  description: >-
    LitVar allows the search and retrieval of variant relevant information
    from the biomedical literature and shows key biological relations between a variant
    and its close related entities (e.g. genes, diseases, and drugs). The LitVar results
    are automatically extracted (with regular updates) from over 27 million PubMed
    articles as well as applicable full-text articles in PubMed Central. See 
    https://www.ncbi.nlm.nih.gov/CBBresearch/Lu/Demo/LitVar/api.html for details.
  termsOfService: https://www.ncbi.nlm.nih.gov/home/about/policies/
  contact:
    name: Zhiyong Lu
    email: luzh@ncbi.nlm.nih.gov
  x-translator:
    infores: "infores:litvar"
    component: KP
    team:
      - Service Provider
    biolink-version: "3.5.0"
servers:
- url: https://www.ncbi.nlm.nih.gov/research/bionlp/litvar/api/v1
  description: Production server
  x-maturity: production
tags:
- name: variant
- name: translator
paths:
  "/entity/litvar/{variantid}":
    get:
      summary: This will allow you to retrieve information about a variant given its VarID.
      parameters:
      - name: variantid
        in: path
        example: "rs121913527##"
        description: rsid
        required: true
        schema:
          type: string
      responses:
        '200':
          description: publications mentioned the submitted variant
      x-bte-kgs-operations:
      - "$ref": "#/components/x-bte-kgs-operations/variant_located_in_gene"
components:
## knowledge_level / agent_type: gene assignments seem to happen in automated build process 
##   https://www.ncbi.nlm.nih.gov/books/NBK21088/#_ch5_ch5_s4_
  x-bte-kgs-operations:
    variant_located_in_gene:
    ## API cannot do the reverse operation
    - supportBatch: false
      useTemplating: true
      inputs:
      - id: DBSNP
        semantic: SequenceVariant
      parameters:
        variantid: "{{ queryInputs | rmPrefix() }}%23%23"  ## no prefix
      outputs:
      - id: NCBIGene
        semantic: Gene
      predicate: is_sequence_variant_of
      source: "infores:dbsnp"
      knowledge_type: knowledge_assertion
      agent_type: automated_agent
      response_mapping:
        "$ref": "#/components/x-bte-response-mapping/variant_located_in_gene"
      testExamples:
        - qInput: "DBSNP:rs121913527"   
          oneOutput: "NCBIGene:3845"    ## KRAS
      ## another example input is rs1193171808
  ## raw query example: https://www.ncbi.nlm.nih.gov/research/bionlp/litvar/api/v1/entity/litvar/rs121913527%23%23
  x-bte-response-mapping:
    variant_located_in_gene:
      NCBIGene: gene.id  ## no prefix
      ref_url: links.url
