---
openapi: 3.0.3
info:
  version: '1.0'
  title: QuickGO API
  description: >-
    The QuickGO REST API provides access to key biological data from QuickGO
    and GOA. The services provide a unified interface to query information about ontology
    terms from GO (the Gene Ontology) and ECO (the Evidence & Conclusion Ontology),
    Gene Ontology annotations from the EBI's GOA database, and gene products (proteins
    from UniProt, RNA from RNAcentral and complexes from ComplexPortal).
    See https://www.ebi.ac.uk/QuickGO/api/index.html for more details.
  termsOfService: https://www.ebi.ac.uk/QuickGO/services
  contact:
    name: pharmgkb help desk
    x-role: responsible developer
    email: help@pharmgkb.org
  x-translator:
    infores: "infores:ebi-quick-go"
    component: KP
    team:
      - Service Provider
    biolink-version: "2.2.13"
servers:
- url: https://www.ebi.ac.uk/QuickGO/services
  description: Production server
  x-maturity: production
tags:
- name: ontology
- name: translator
paths:
  "/ontology/go/terms/{goid}/children":
    get:
      summary: retrieve the children of specified ontology terms
      parameters:
      - name: goid
        in: path
        description: Put Gene Ontology ID here, e.g. GO:0000082
        required: true
        example: GO:0000082
        schema:
          type: string
      responses:
        '200':
          description: A gene ontology annotation object
      x-bte-kgs-operations:
      - "$ref": "#/components/x-bte-kgs-operations/ma_has_subclass_ma"
components:
  x-bte-kgs-operations:
    ## BIG NOTE: there is likely more data in this API, but want to add stuff that would be helpful for use cases, that we regularly update
    ma_has_subclass_ma:
    - inputs:
      - id: GO
        semantic: MolecularActivity
      source: "infores:go"
      predicate: superclass_of  ## this is current biolink, same meaning as "has_subclass"
      outputs:
      - id: GO
        semantic: MolecularActivity
      parameters:
        goid: "{inputs[0]}"  ## has prefix (GO)
      supportBatch: false
      response_mapping:
        "$ref": "#/components/x-bte-response-mapping/ma_has_subclass_ma"
      # testExamples:
      #   - qInput: "GO:0000082"     ## G1/S transition of mitotic cell cycle
      #     oneOutput: "GO:2000045"  ## regulation of G1/S transition of mitotic cell cycle
  x-bte-response-mapping:
    ma_has_subclass_ma:
      GO: results.children.id  ## has prefix (GO)
      "biolink:original_predicate": results.children.relation
